export const CALL_YOUTUBE_API: string = "CALL_YOUTUBE_API";
export const SEND_YOUTUBE_API_SUCCESS: string = "SEND_YOUTUBE_API_SUCCESS";
export const SEND_YOUTUBE_API_REQUEST: string = "SEND_YOUTUBE_API_REQUEST";
export const SEND_YOUTUBE_API_FAILED: string = "SEND_YOUTUBE_API_FAILED";
