export const CALL_YOUTUBE_API = "CALL_YOUTUBE_API";
export const SET_YOUTUBE_LOADER = "SET_YOUTUBE_LOADER";
export const SEND_YOUTUBE_API_SUCCESS: string = "SEND_YOUTUBE_API_SUCCESS";
export const SEND_YOUTUBE_API_REQUEST: string = "SEND_YOUTUBE_API_REQUEST";
export const SEND_YOUTUBE_API_FAILED: string = "SEND_YOUTUBE_API_FAILED";
